#!/usr/bin/env python

import argparse
from json import load
from requests import get, post
from time import sleep

class DeisProxy(object):
    def __init__(self, settings_path):
        self.settings = self._read_settings(settings_path)

    @property
    def _app_names(self):
        return self._get_setting('services').keys()

    @property
    def _auth_header(self):
        return {'Authorization': 'token %s' % self._auth_token}

    @property
    def _auth_token(self):
        return self._get_setting('deis', 'token')

    @property
    def _controller_url(self):
        return self._get_setting('deis', 'controller')

    def config_all(self, **kwargs):
        for app_name in self._app_names:
            self.config(app_name)

    def config(self, app_name, **kwargs):
        updates = self._config_updates(app_name)
        if updates:
            print 'About to update config for %s with:' % app_name
            print self._format_config(updates)
            self._deploy_config_updates(app_name, updates)
            self._validate_deployed_config(app_name)
            print 'Success!'
        else:
            print 'Nothing to update for %s' % app_name

        print ''

    def _deploy_config_updates(self, app_name, updates):
        self._deis_post('/v1/apps/%s/config/' % app_name,
                {'values': updates})

    def _validate_deployed_config(self, app_name):
        updates = self._config_updates(app_name)
        if updates:
            config = self._format_config(updates)
            raise RuntimeError(
                'Failed to update config for %s:\n%s' % (app_name, config))

    def _config_updates(self, app_name):
        proposed = self._proposed_config(app_name)
        deployed = self._deployed_config(app_name)

        result = self._new_and_changed(proposed, deployed)
        result.update(self._config_values_to_clear(proposed, deployed))
        return result

    def _proposed_config(self, app_name):
        return self._get_setting('services', app_name, 'environment')

    def _deployed_config(self, app_name):
        response_body = self._deis_get('/v1/apps/%s/config/' % app_name)
        return response_body['values']

    def _new_and_changed(self, proposed, deployed):
        proposed_set = self._set_from_dict(proposed)
        deployed_set = self._set_from_dict(deployed)
        return dict(proposed_set - deployed_set)

    def scale_all(self, **kwargs):
        for app_name in self._app_names:
            self.scale(app_name)

    def scale(self, app_name, **kwargs):
        updates = self._scale_updates(app_name)
        if updates:
            print 'About to update scale for %s with:' % app_name
            print self._format_scale(updates)
            self._deploy_scale_updates(app_name, updates)
            self._validate_deployed_scale(app_name)
            print 'Success!'
        else:
            print 'Nothing to update for %s' % app_name

        print ''

    def stop_all(self, **kwargs):
        for app_name in self._app_names:
            self.stop(app_name)

    def stop(self, app_name, **kwargs):
        updates = self._scale_updates_for_stop(app_name)
        if updates:
            print 'Attempting to stop %s' % app_name
            print 'About to update scale for %s with:' % app_name
            print self._format_scale(updates)
            self._deploy_scale_updates(app_name, updates)
            self._validate_stopped(app_name)
            print 'Success!'
        else:
            print '%s already stopped' % app_name

        print ''

    def _scale_updates(self, app_name):
        proposed = self._proposed_scale(app_name)
        deployed = self._deployed_scale(app_name)

        result = self._new_and_changed(proposed, deployed)
        result.update(self._scale_values_to_zero(proposed, deployed))
        return result

    def _scale_updates_for_stop(self, app_name):
        proposed = self._dict_values_to_zero(self._deployed_scale(app_name))
        deployed = self._deployed_scale(app_name)
        return self._new_and_changed(proposed, deployed)

    def _proposed_scale(self, app_name):
        return self._dict_values_to_string(
            self._get_setting('services', app_name, 'scale'))

    def _deployed_scale(self, app_name):
        response_body = self._deis_get('/v1/apps/%s/' % app_name)
        return self._dict_values_to_string( response_body['structure'] )

    @staticmethod
    def _dict_values_to_zero(d):
        for key in d:
            d[key] = "0"
        return d

    @staticmethod
    def _dict_values_to_string(d):
        for key in d:
            d[key] = str(d[key])
        return d

    def _deploy_scale_updates(self, app_name, updates):
        print 'About to post scale updates'
        self._deis_post('/v1/apps/%s/scale/' % app_name, updates)
        print 'Scale updates posted'

    def _validate_stopped(self, app_name):
        updates = self._scale_updates_for_stop(app_name)
        if updates:
            scale = self._format_scale(updates)
            raise RuntimeError(
                'Failed to update scale for %s:\n%s' % (app_name, scale))

    def _validate_deployed_scale(self, app_name):
        updates = self._scale_updates(app_name)
        if updates:
            scale = self._format_scale(updates)
            raise RuntimeError(
                'Failed to update scale for %s:\n%s' % (app_name, scale))

    def _deis_get(self, endpoint):
        response = get(self._endpoint_url(endpoint), headers=self._auth_header)
        response.raise_for_status()
        return response.json()

    def _deis_post(self, endpoint, data):
        headers = self._auth_header
        headers.update({'Content-Type': 'application/json'})
        response = post(self._endpoint_url(endpoint), json=data, headers=headers)
        response.raise_for_status()
        if response.encoding == 'application/json':
            return response.json()

    def _endpoint_url(self, endpoint):
        return self._controller_url + endpoint

    def _get_setting(self, *args):
        setting = self.settings.copy()
        for arg in args:
            setting = setting[arg]
        return setting

    @staticmethod
    def _config_values_to_clear(proposed, deployed):
        keys = set(deployed.keys()) - set(proposed.keys())
        return { key: None for key in keys }

    @staticmethod
    def _scale_values_to_zero(proposed, deployed):
        keys = set(deployed.keys()) - set(proposed.keys())
        return { key: 0 for key in keys }

    @staticmethod
    def _format_config(d):
        config = ''
        for key in sorted(d.keys()):
            config = config + '  %s=%s\n' % (key, d[key])
        return config

    @staticmethod
    def _format_scale(d):
        scale = ''
        for key in sorted(d.keys()):
            scale = scale + '  %s: %s\n' % (key, d[key])
        return scale

    @staticmethod
    def _read_settings(path):
        with open(path) as ofile:
            return load(ofile)

    @staticmethod
    def _set_from_dict(d):
        return set([(k, v) for k, v in d.iteritems()])

def main():
    parser = create_parser()
    parsed_args = parser.parse_args()
    deis_proxy = DeisProxy(parsed_args.config)
    subcommand = parsed_args.subcommand
    getattr(deis_proxy, subcommand.replace('-', '_'))(**vars(parsed_args))

def create_parser():
    parser = argparse.ArgumentParser(prog='ptero-deploy-deis')
    parser.add_argument('--config', action='store', required=True, help='config help')
    subparsers = parser.add_subparsers(dest='subcommand', help='sub-command help')

    subparsers.add_parser('config-all', help='Update configuration for all apps')

    config_parser = subparsers.add_parser('config', help='Update configuration for one app')
    config_parser.add_argument('app_name', help='Name of app to configure')

    subparsers.add_parser('scale-all', help='Scale all apps')

    scale_parser = subparsers.add_parser('scale', help='Scale one app')
    scale_parser.add_argument('app_name', help='Name of app to scale')

    subparsers.add_parser('stop-all', help='Stop all apps')

    stop_parser = subparsers.add_parser('stop', help='Stop one app')
    stop_parser.add_argument('app_name', help='Name of app to stop')

    return parser


if __name__ == '__main__':
    main()
