#!/usr/bin/env bash

source $PTERO_COMMON

DEPLOYMENT_CONFIG=${1?"Usage: $0 DEPLOYMENT_CONFIG"}

log "Setting app configs..."
log

"${PTERO_DIR}/deployment/libexec/deploy-deis-proxy" --config "${DEPLOYMENT_CONFIG}" config-all
