#!/usr/bin/env bash

set -e
source $PTERO_COMMON

DEPLOYMENT_CONFIG=${1?"Usage: $0 DEPLOYMENT_CONFIG"}

log "Stopping apps..."
log

"${PTERO_DIR}/deployment/libexec/deploy-deis-proxy" --config "${DEPLOYMENT_CONFIG}" stop-all
